name: data-access-layer CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      
      - name: install dotnet '8.0.100-rc.2.23502.2'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100-rc.2.23502.2'

      - name: restore dependencies
        run: dotnet restore

      - name: build
        run: |
            dotnet build --configuration Release --no-restore
            dotnet publish -c Release -o ./published

      - name: test
        run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage" -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover

      - name: code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: data-access-layer.Tests/TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: add coverage PR comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
           recreate: true
           path: code-coverage-results.md

      - name: test
        run: dotnet test --no-restore --verbosity normal data-access-layer.Tests/ --collect:"XPlat Code Coverage" -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover

      # Execute code coverage for unit tests results in the solution
      - name: code coverage badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        id: create_coverage_badge
        with:
           label: code coverage
           color: green
           path: data-access-layer.Tests\TestResults\coverage.opencover.xml
           gist-filename: code-coverage.json
           gist-id: 6139c93439673c361cd0aebd8462e298
           gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}

      - name: print code coverage
        run: echo "Code coverage percentage ${{steps.create_coverage_badge.outputs.percentage}}%"
