name: data-access-layer CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
      
      - name: install dotnet '8.0.100-rc.2.23502.2'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.100-rc.2.23502.2'

      - name: restore dependencies
        run: dotnet restore

      - name: build
        run: |
            dotnet build --configuration Release --no-restore
            dotnet publish -c Release -o ./published

      - name: test
        run: dotnet test --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutput=TestResults/ -p:CoverletOutputFormat=opencover

      # - name: code coverage report
      #   uses: irongut/CodeCoverageSummary@v1.3.0
      #   with:
      #     filename: coverage/**/coverage.cobertura.xml
      #     badge: true
      #     fail_below_min: true
      #     format: markdown
      #     hide_branch_rate: false
      #     hide_complexity: true
      #     indicators: true
      #     output: both
      #     thresholds: '60 80'
